kind = "api"
previewPath = "/"
title = "Friday AI Bot"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 5001
name = "Friday AI Bot"
paths = ["/"]

[services.development]
run = "bash -c 'PORT=5001 python /home/runner/workspace/keep_alive.py'"

[services.production]

[services.production.run]
args = ["python", "main.py"]

[services.production.run.env]
PORT = "5001"

[services.production.health.startup]
path = "/health"
